### ISSUE TITLE
Exception in PluginLineMarkerProvider

### ISSUE THREAD

**Issue by Minecrell** [minecraft-dev/MinecraftDev#116]
I get this error every time I open my test project when testing MinecraftDev:

```
Access is allowed from event dispatch thread only.
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@1d975cec Current thread: Thread[JobScheduler FJ pool 0/4,4,main] 1677319083 SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.3#IC-163.7743.44 IDEA, eap:false, os:Linux 4.4.38-1-lts, java-version:JetBrains s.r.o 1.8.0_112-release-408-b2,6,main] 1599633588

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:501)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1010)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:999)
	at com.intellij.openapi.application.impl.LaterInvocator.getCurrentModalityState(LaterInvocator.java:318)
	at com.intellij.openapi.application.impl.ApplicationImpl.getCurrentModalityState(ApplicationImpl.java:666)
	at com.intellij.openapi.application.ModalityState.current(ModalityState.java:69)
	at com.demonwav.mcdev.util.UtilKt.invokeLater(Util.kt:36)
	at com.demonwav.mcdev.util.Util.invokeLater(Util.kt:58)
	at com.demonwav.mcdev.platform.MinecraftModule.getInstance(MinecraftModule.java:117)
	at com.demonwav.mcdev.insight.PluginLineMarkerProvider.getLineMarkerInfo(PluginLineMarkerProvider.java:46)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:186)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Minecrell** [comment]
Fixed in https://github.com/minecraft-dev/MinecraftDev/commit/09b5ed5313b8a207f6b68bfd00482183ff6453fc
