### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by JBYoshi** [minecraft-dev/MinecraftDev#120]
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater.addSubtreeToUpdate(AbstractTreeUpdater.java:163)
	at com.intellij.ide.util.treeView.AbstractTreeUi$60.perform(AbstractTreeUi.java:3689)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1835)
	at com.intellij.ide.util.treeView.AbstractTreeUi.addSubtreeToUpdate(AbstractTreeUi.java:3685)
	at com.intellij.ide.util.treeView.AbstractTreeUi.addSubtreeToUpdate(AbstractTreeUi.java:3666)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.addSubtreeToUpdate(AbstractTreeBuilder.java:189)
	at com.intellij.ide.projectView.impl.AbstractProjectViewPSIPane.updateFromRoot(AbstractProjectViewPSIPane.java:242)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.refresh(ProjectViewImpl.java:777)
	at com.demonwav.mcdev.platform.MinecraftModule.updateModules(MinecraftModule.java:254)
	at com.demonwav.mcdev.platform.MinecraftModuleType.addOption(MinecraftModuleType.java:51)
	at com.demonwav.mcdev.buildsystem.gradle.AbstractDataService.findParent(AbstractDataService.java:168)
	at com.demonwav.mcdev.buildsystem.gradle.AbstractDataService.lambda$null$0(AbstractDataService.java:99)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.demonwav.mcdev.buildsystem.gradle.AbstractDataService.lambda$setupModules$1(AbstractDataService.java:99)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:879)
	at com.demonwav.mcdev.buildsystem.gradle.AbstractDataService.setupModules(AbstractDataService.java:92)
	at com.demonwav.mcdev.buildsystem.gradle.AbstractDataService.lambda$checkModule$3(AbstractDataService.java:145)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.demonwav.mcdev.buildsystem.gradle.AbstractDataService.checkModule(AbstractDataService.java:121)
	at com.demonwav.mcdev.platform.forge.gradle.ForgeDataService.importData(ForgeDataService.java:42)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.doImportData(ProjectDataManager.java:246)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:143)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:198)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:204)
	at com.intellij.openapi.externalSystem.service.project.autoimport.ExternalSystemAutoImporter$1.onSuccess(ExternalSystemAutoImporter.java:86)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:442)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5.run(ExternalSystemUtil.java:495)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Minecrell** [comment]
The module detection was recently replaced by facets so this error shouldn't exist anymore.
