### ISSUE TITLE
KotlinNullPointerException when copying code

### ISSUE THREAD

**Issue by Barteks2x** [minecraft-dev/MinecraftDev#145]
I got it only a few times without any clearly visible pattern:

```
null
kotlin.KotlinNullPointerException
	at com.demonwav.mcdev.util.McPsiClass.getFullQualifiedName(McPsiClass.kt:29)
	at com.demonwav.mcdev.platform.mixin.util.MemberReferencePsiKt.getQualifiedMemberReference(MemberReferencePsi.kt:57)
	at com.demonwav.mcdev.platform.mixin.editor.MixinCopyPasteReferenceProcessor.addReferenceData(MixinCopyPasteReferenceProcessor.kt:52)
	at com.intellij.codeInsight.editorActions.CopyPasteReferenceProcessor.collectTransferableData(CopyPasteReferenceProcessor.java:60)
	at com.intellij.codeInsight.editorActions.CopyHandler.lambda$doExecute$0(CopyHandler.java:94)
	at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:267)
	at com.intellij.codeInsight.editorActions.CopyHandler.doExecute(CopyHandler.java:92)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:95)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:104)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Minecrell** [comment]
\o/
According to the stack trace you were copying code while you got this stack trace. Could you share the code you are copying when you get it the next time?

**Comment by Barteks2x** [comment]
It happened when I opened a project, I'm almost sure I didn't copy anything.

**Comment by Minecrell** [comment]
Then you should have different stack traces, the one above is something related to copy-paste? Can you check if the stack traces are really the same?

**Comment by Barteks2x** [comment]
That was the stacktrace I got when opening a project, that's when I copied it

**Comment by Minecrell** [comment]
IntelliJ IDEA groups similar exceptions together, so sometimes you can click "Next" (or something like that) to see the others.

**Comment by Barteks2x** [comment]
There was only one. Unless IDEA saves exception list between restarts, then it might be when I copied something much earlier and didn't notice.

**Comment by DemonWav** [comment]
This one doesn't seem to make sense for a few reasons. We haven't been able to figure out how to reproduce it regardless of what we try. Has this happened to you since you posted this issue?

**Comment by Barteks2x** [comment]
Not yet, but I may have an idea for what might cause it.

**Comment by Barteks2x** [comment]
Actually it must have been from previous open project and I only noticed it when I opened new one. The project I opened didn't even have any mixins and this exception mentions mixins.

**Comment by Minecrell** [comment]
@Barteks2x 
Right now the code is even run for projects without Mixin as dependencies. It is possible that there is an error in a project without Mixins.

**Comment by Barteks2x** [comment]
It wasn't even a Minecraft project. It was my local clone of flow-noise library.

**Comment by Minecrell** [comment]
@Barteks2x 
It runs on literally **every** project. The code where you get the error only records references to fields and methods when you copy code, the actual Mixin code comes later.

**Comment by Barteks2x** [comment]
There was a compile error in the project when I loaded it, but I wasn't able to reproduce it later when I added the same compile error.

**Comment by Barteks2x** [comment]
I found a way to reproduce it, now I need to simplify it.

**Comment by Barteks2x** [comment]
This is the simplest code I found that shows the error:

```java
public class Test {
    Object o = new Object() {
        Object o1 = null;
        Object o2 = o1; // copying o1 from here throws exception
    };
}
```

**Comment by DemonWav** [comment]
Thanks for narrowing this down.
