### ISSUE TITLE
java.lang.UnsupportedOperationException: Unsupported expression type

### ISSUE THREAD

**Issue by Barteks2x** [minecraft-dev/MinecraftDev#161]
I got this exception, I'm not exactly sure when or how:
```
Unsupported expression type: PsiPrefixExpression:!entity.world.isBlockLoaded(pos)
java.lang.UnsupportedOperationException: Unsupported expression type: PsiPrefixExpression:!entity.world.isBlockLoaded(pos)
	at com.demonwav.mcdev.util.McPsiUtil.getConstantStringValue(McPsiUtil.kt:205)
	at com.demonwav.mcdev.util.McPsiUtil.getConstantStringValue(McPsiUtil.kt:201)
	at com.demonwav.mcdev.platform.mixin.reference.InjectionPointType.resolveReference(InjectionPointType.kt:36)
	at com.demonwav.mcdev.platform.mixin.reference.InjectionPointType.isUnresolved(InjectionPointType.kt:46)
	at com.demonwav.mcdev.platform.mixin.inspection.reference.UnresolvedReferenceInspection$Visitor.checkResolved(UnresolvedReferenceInspection.kt:63)
	at com.demonwav.mcdev.platform.mixin.inspection.reference.UnresolvedReferenceInspection$Visitor.visitNameValuePair(UnresolvedReferenceInspection.kt:58)
	at com.intellij.psi.impl.source.tree.java.PsiNameValuePairImpl.accept(PsiNameValuePairImpl.java:217)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:280)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:249)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:123)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:212)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:141)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$0(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Barteks2x** [comment]
I think it may actually be the same as #146, I was able to get very similar error after pasting the code from the message into annotation.
