### ISSUE TITLE
IDE Fatal Error

### ISSUE THREAD

**Issue by allanf181** [minecraft-dev/MinecraftDev#176]
![image](https://cloud.githubusercontent.com/assets/14101716/23824997/687d2ca8-0660-11e7-8abd-7223a0497b9b.png)
IntelliJ IDEA (Community Edition) 2017.1 EAP
Build #IC-171.3780.15, built on March 8, 2017
JRE: 1.8.0_112-release-736-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by Minecrell** [comment]
Please copy the contents of the details block into a code block here.

**Comment by allanf181** [comment]
```java
@NotNull method com/demonwav/mcdev/platform/forge/ForgeModule.getMcmod must not return null
java.lang.IllegalStateException: @NotNull method com/demonwav/mcdev/platform/forge/ForgeModule.getMcmod must not return null
	at com.demonwav.mcdev.platform.forge.ForgeModule.$$$reportNull$$$0(ForgeModule.java)
	at com.demonwav.mcdev.platform.forge.ForgeModule.getMcmod(ForgeModule.java:115)
	at com.demonwav.mcdev.platform.forge.ForgeFileIconProvider.getIcon(ForgeFileIconProvider.java:38)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1125)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
