### ISSUE TITLE
IDE Fatal Error

### ISSUE THREAD

**Issue by allanf181** [minecraft-dev/MinecraftDev#178]
![image](https://cloud.githubusercontent.com/assets/14101716/23827891/f7c1cce2-069d-11e7-95bd-5d1867cec86c.png)
IntelliJ IDEA (Community Edition) 2017.1 EAP
Build #IC-171.3780.15, built on March 8, 2017
JRE: 1.8.0_112-release-736-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```java
Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
	at com.demonwav.mcdev.facet.MinecraftFacet.getInstance(MinecraftFacet.kt)
	at com.demonwav.mcdev.platform.forge.ForgeFileIconProvider.getIcon(ForgeFileIconProvider.java:39)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
	at com.intellij.ui.IconDeferrerImpl.deferImpl(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:170)
	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:243)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:123)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:60)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1125)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
	at com.demonwav.mcdev.facet.MinecraftFacet.getInstance(MinecraftFacet.kt)
	at com.demonwav.mcdev.platform.forge.ForgeFileIconProvider.getIcon(ForgeFileIconProvider.java:39)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
	at com.intellij.ui.IconDeferrerImpl.deferImpl(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:170)
	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:243)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:123)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:60)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1125)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
	at com.demonwav.mcdev.facet.MinecraftFacet.getInstance(MinecraftFacet.kt)
	at com.demonwav.mcdev.platform.forge.ForgeFileIconProvider.getIcon(ForgeFileIconProvider.java:39)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
	at com.intellij.ui.IconDeferrerImpl.deferImpl(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:170)
	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:243)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:123)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:60)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1125)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
	at com.demonwav.mcdev.facet.MinecraftFacet.getInstance(MinecraftFacet.kt)
	at com.demonwav.mcdev.platform.forge.ForgeFileIconProvider.getIcon(ForgeFileIconProvider.java:39)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
	at com.intellij.ui.IconDeferrerImpl.deferImpl(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:170)
	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:243)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:123)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:60)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1125)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
	at com.demonwav.mcdev.facet.MinecraftFacet.getInstance(MinecraftFacet.kt)
	at com.demonwav.mcdev.platform.forge.ForgeFileIconProvider.getIcon(ForgeFileIconProvider.java:39)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
	at com.intellij.ui.IconDeferrerImpl.deferImpl(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:170)
	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:243)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:123)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:60)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1125)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
	at com.demonwav.mcdev.facet.MinecraftFacet.getInstance(MinecraftFacet.kt)
	at com.demonwav.mcdev.platform.forge.ForgeFileIconProvider.getIcon(ForgeFileIconProvider.java:39)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
	at com.intellij.ui.IconDeferrerImpl.deferImpl(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:170)
	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:243)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:123)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:60)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1125)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
	at com.demonwav.mcdev.facet.MinecraftFacet.getInstance(MinecraftFacet.kt)
	at com.demonwav.mcdev.platform.forge.ForgeFileIconProvider.getIcon(ForgeFileIconProvider.java:39)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
	at com.intellij.ui.IconDeferrerImpl.deferImpl(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:170)
	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:243)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:123)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:60)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1125)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by DemonWav** [comment]
And what version of the plugin?

**Comment by allanf181** [comment]
Version: 2017.1-0.5.8

**Comment by allanf181** [comment]
More 2 errors now.

```java
Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
	at com.demonwav.mcdev.facet.MinecraftFacet.getInstance(MinecraftFacet.kt)
	at com.demonwav.mcdev.platform.forge.ForgeFileIconProvider.getIcon(ForgeFileIconProvider.java:39)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
	at com.intellij.ui.IconDeferrerImpl.deferImpl(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:170)
	at com.intellij.psi.impl.ElementBase.getElementIcon(ElementBase.java:243)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:123)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:60)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1125)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

````java
Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.demonwav.mcdev.facet.MinecraftFacet.getInstance, parameter module
	at com.demonwav.mcdev.facet.MinecraftFacet.getInstance(MinecraftFacet.kt)
	at com.demonwav.mcdev.platform.forge.ForgeFileIconProvider.getIcon(ForgeFileIconProvider.java:39)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:176)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:140)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1125)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
