### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by DemonWav** [minecraft-dev/MinecraftDev#194]
```
null
kotlin.KotlinNullPointerException
	at com.demonwav.mcdev.util.PsiBytecodeUtil.appendInternalName(PsiBytecodeUtil.kt:75)
	at com.demonwav.mcdev.util.PsiBytecodeUtil.appendDescriptor(PsiBytecodeUtil.kt:85)
	at com.demonwav.mcdev.util.PsiBytecodeUtil.appendDescriptor(PsiBytecodeUtil.kt:138)
	at com.demonwav.mcdev.util.PsiBytecodeUtil.getDescriptor(PsiBytecodeUtil.kt:133)
	at com.demonwav.mcdev.util.MemberReferencePsiKt$findMethods$1.test(MemberReferencePsi.kt:30)
	at com.demonwav.mcdev.util.MemberReferencePsiKt$findMethods$1.test(MemberReferencePsi.kt)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
	at com.demonwav.mcdev.util.MemberReference.resolve(MemberReference.kt:86)
	at com.demonwav.mcdev.platform.mixin.inspection.injector.InjectorType$REDIRECT.expectedMethodSignature(InjectorType.kt:83)
	at com.demonwav.mcdev.platform.mixin.inspection.injector.InvalidInjectorMethodSignatureInspection$Visitor.visitMethod(InvalidInjectorMethodSignatureInspection.kt:63)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:284)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:305)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

```
null
kotlin.KotlinNullPointerException
	at com.demonwav.mcdev.util.PsiBytecodeUtil.appendInternalName(PsiBytecodeUtil.kt:75)
	at com.demonwav.mcdev.util.PsiBytecodeUtil.appendDescriptor(PsiBytecodeUtil.kt:85)
	at com.demonwav.mcdev.util.PsiBytecodeUtil.appendDescriptor(PsiBytecodeUtil.kt:138)
	at com.demonwav.mcdev.util.PsiBytecodeUtil.getDescriptor(PsiBytecodeUtil.kt:133)
	at com.demonwav.mcdev.util.MemberReference.match(MemberReference.kt:45)
	at com.demonwav.mcdev.platform.mixin.reference.target.MethodTargetReference$FindUsagesVisitor.visitMethodUsage(MethodTargetReference.kt:38)
	at com.demonwav.mcdev.platform.mixin.reference.target.MethodTargetReference$CompiledMethodsVisitor.visitMethodCallExpression(MethodTargetReference.kt:67)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:141)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:41)
	at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:66)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
	at com.demonwav.mcdev.platform.mixin.reference.target.TargetReference.resolve(TargetReference.kt:94)
	at com.demonwav.mcdev.platform.mixin.reference.target.TargetReference.isUnresolved(TargetReference.kt:77)
	at com.demonwav.mcdev.platform.mixin.inspection.reference.UnresolvedReferenceInspection$Visitor.checkResolved(UnresolvedReferenceInspection.kt:63)
	at com.demonwav.mcdev.platform.mixin.inspection.reference.UnresolvedReferenceInspection$Visitor.visitNameValuePair(UnresolvedReferenceInspection.kt:58)
	at com.intellij.psi.impl.source.tree.java.PsiNameValuePairImpl.accept(PsiNameValuePairImpl.java:217)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:305)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:222)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

```
null
kotlin.KotlinNullPointerException
	at com.demonwav.mcdev.util.PsiBytecodeUtil.appendInternalName(PsiBytecodeUtil.kt:75)
	at com.demonwav.mcdev.util.PsiBytecodeUtil.appendDescriptor(PsiBytecodeUtil.kt:85)
	at com.demonwav.mcdev.util.PsiBytecodeUtil.appendDescriptor(PsiBytecodeUtil.kt:138)
	at com.demonwav.mcdev.util.PsiBytecodeUtil.getDescriptor(PsiBytecodeUtil.kt:133)
	at com.demonwav.mcdev.util.MemberReference.match(MemberReference.kt:45)
	at com.demonwav.mcdev.platform.mixin.reference.target.MethodTargetReference$FindUsagesVisitor.visitMethodUsage(MethodTargetReference.kt:38)
	at com.demonwav.mcdev.platform.mixin.reference.target.MethodTargetReference$CompiledMethodsVisitor.visitMethodCallExpression(MethodTargetReference.kt:67)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:141)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:41)
	at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:66)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
	at com.demonwav.mcdev.platform.mixin.reference.target.TargetReference.resolve(TargetReference.kt:94)
	at com.demonwav.mcdev.platform.mixin.reference.target.TargetReference.isUnresolved(TargetReference.kt:77)
	at com.demonwav.mcdev.platform.mixin.inspection.reference.UnresolvedReferenceInspection$Visitor.checkResolved(UnresolvedReferenceInspection.kt:63)
	at com.demonwav.mcdev.platform.mixin.inspection.reference.UnresolvedReferenceInspection$Visitor.visitNameValuePair(UnresolvedReferenceInspection.kt:58)
	at com.intellij.psi.impl.source.tree.java.PsiNameValuePairImpl.accept(PsiNameValuePairImpl.java:217)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:305)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:222)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:151)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:222)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Minecrell** [comment]
Hard to tell what's causing this without example code where this error is thrown? What did you do when this error showed up?

**Comment by gabizou** [comment]
@Minecrell I'm not sure when or why it was thrown. I just remember seeing the red error icon blinking and thought to report it. I couldn't say exactly what caused it, but I'm still guessing that it's going to be finicky about files that were existing and then suddenly didn't exist (like when re-creating SpongeEventFactory).

**Comment by DemonWav** [comment]
@Minecrell imo this is pretty clear that it's caused by `resolve()` on `PsiClassType` returning null.

**Comment by DemonWav** [comment]
Also, it's an inspection, so it's run on all the code in the file.

**Comment by DemonWav** [comment]
@Minecrell @gabizou is this something we're going to get any clarity in, or should I just close it? No reason to keep this open if it's just going to get dusty.

**Comment by Minecrell** [comment]
I will happily fix issues like these but it's hard to tell what is causing them exactly without a way to reproduce. I think we should close it and fix it whenever it is reported again (it seems to happen only under very special circumstances, otherwise someone else would have been able to reproduce this).
