### ISSUE TITLE
StackOverflowError when trying to inherit itself

### ISSUE THREAD

**Issue by jaime29010** [minecraft-dev/MinecraftDev#83]
It starts happening as soon as you try to implement or extend the same class
It happens on the version 2016.2-0.3.7

This is the exception that gets thrown by IDEA.

```
null
java.lang.StackOverflowError
    at gnu.trove.TObjectCanonicalHashingStrategy.computeHashCode(TObjectCanonicalHashingStrategy.java:8)
    at com.intellij.util.containers.ConcurrentHashMap.hash(ConcurrentHashMap.java:3602)
    at com.intellij.util.containers.ConcurrentHashMap.get(ConcurrentHashMap.java:945)
    at com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.get(ConcurrentWeakKeySoftValueHashMap.java:231)
    at com.intellij.psi.impl.source.resolve.ResolveCache$2.get(ResolveCache.java:108)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:182)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:745)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:734)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:377)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:370)
    at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:145)
    at com.intellij.psi.impl.source.PsiClassReferenceType.resolve(PsiClassReferenceType.java:93)
    at com.intellij.psi.impl.PsiClassImplUtil.getSuperClass(PsiClassImplUtil.java:784)
    at com.intellij.psi.impl.PsiClassImplUtil.b(PsiClassImplUtil.java:836)
    at com.intellij.psi.impl.PsiClassImplUtil.getSupers(PsiClassImplUtil.java:795)
    at com.intellij.psi.impl.source.PsiClassImpl.getSupers(PsiClassImpl.java:246)
    at com.demonwav.mcdev.util.McPsiUtil.extendsOrImplementsClass(McPsiUtil.java:77)
    at com.demonwav.mcdev.util.McPsiUtil.extendsOrImplementsClass(McPsiUtil.java:82)
    at com.demonwav.mcdev.util.McPsiUtil.extendsOrImplementsClass(McPsiUtil.java:82)
       ...
```

**Comment by DemonWav** [comment]
Should be fixed in 111e9c8. Will push a new build soon.
