### ISSUE TITLE
CME in updateModules

### ISSUE THREAD

**Issue by aikar** [minecraft-dev/MinecraftDev#91]
2016.2-0.3.7

```
null
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater.addSubtreeToUpdate(AbstractTreeUpdater.java:163)
	at com.intellij.ide.util.treeView.AbstractTreeUi$60.perform(AbstractTreeUi.java:3696)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1832)
	at com.intellij.ide.util.treeView.AbstractTreeUi.addSubtreeToUpdate(AbstractTreeUi.java:3692)
	at com.intellij.ide.util.treeView.AbstractTreeUi.addSubtreeToUpdate(AbstractTreeUi.java:3673)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.addSubtreeToUpdate(AbstractTreeBuilder.java:189)
	at com.intellij.ide.projectView.impl.AbstractProjectViewPSIPane.updateFromRoot(AbstractProjectViewPSIPane.java:221)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.refresh(ProjectViewImpl.java:745)
	at com.demonwav.mcdev.platform.MinecraftModule.updateModules(MinecraftModule.java:247)
	at com.demonwav.mcdev.platform.MinecraftModuleType.removeOption(MinecraftModuleType.java:85)
	at com.demonwav.mcdev.buildsystem.maven.AbstractMavenImporter.resolve(AbstractMavenImporter.java:103)
	at org.jetbrains.idea.maven.project.MavenProjectsTree.resolve(MavenProjectsTree.java:1279)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessorResolvingTask.perform(MavenProjectsProcessorResolvingTask.java:44)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessor.doProcessPendingTasks(MavenProjectsProcessor.java:130)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessor.access$000(MavenProjectsProcessor.java:30)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessor$2.run(MavenProjectsProcessor.java:105)
	at org.jetbrains.idea.maven.utils.MavenUtil.lambda$runInBackground$5(MavenUtil.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by DemonWav** [comment]
The issue is in `AbstractTreeUpdater`, the CME happens in the block:

```java
if (!toAdd.isExpired()) {
  final Collection<TreeUpdatePass> yielding = ui.getYeildingPasses();
  for (TreeUpdatePass eachYielding : yielding) {
    final DefaultMutableTreeNode eachNode = eachYielding.getCurrentNode();
    if (eachNode != null) {
      if (eachNode.isNodeAncestor(toAdd.getNode())) {
        eachYielding.setUpdateStamp(newUpdateCount);
      }
    }
  }
}
```

in the for-each block.
