### ISSUE TITLE
YAML bug

### ISSUE THREAD

**Issue by aikar** [minecraft-dev/MinecraftDev#95]
Version 2016.2-0.4.2
```
org.jetbrains.yaml.psi.impl.YAMLQuotedTextImpl cannot be cast to org.jetbrains.yaml.psi.impl.YAMLPlainTextImpl
java.lang.ClassCastException: org.jetbrains.yaml.psi.impl.YAMLQuotedTextImpl cannot be cast to org.jetbrains.yaml.psi.impl.YAMLPlainTextImpl
	at com.demonwav.mcdev.platform.bukkit.yaml.PluginConfigManager.lambda$handleListValue$2(PluginConfigManager.java:204)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.demonwav.mcdev.platform.bukkit.yaml.PluginConfigManager.handleListValue(PluginConfigManager.java:204)
	at com.demonwav.mcdev.platform.bukkit.yaml.PluginConfigManager.lambda$null$0(PluginConfigManager.java:111)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.demonwav.mcdev.platform.bukkit.yaml.PluginConfigManager.lambda$importConfig$1(PluginConfigManager.java:81)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
	at com.demonwav.mcdev.platform.bukkit.yaml.PluginConfigManager.importConfig(PluginConfigManager.java:66)
	at com.demonwav.mcdev.platform.bukkit.yaml.PluginConfigManager.<init>(PluginConfigManager.java:47)
	at com.demonwav.mcdev.platform.bukkit.BukkitModule.setup(BukkitModule.java:76)
	at com.demonwav.mcdev.platform.bukkit.BukkitModule.lambda$new$0(BukkitModule.java:68)
	at org.jetbrains.concurrency.AsyncPromise.setResult(AsyncPromise.java:314)
	at com.demonwav.mcdev.buildsystem.maven.MavenBuildSystem$2.run(MavenBuildSystem.java:301)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by DemonWav** [comment]
I'll fix this by just removing that code. That was code I was writing a long time ago for a feature that never happened, and now that there are so many better features on the way, I probably won't implement it either.
